export const listProject = [
  {
    id: 1,
    name: "Koi Pond - Hà Nội",
    description: "Hồ cá Koi thiết kế tinh tế với kiểu dáng hình tròn.",
    rating: 4.5,
    image: "https://storage.googleapis.com/digital-platform/hinh_anh_goi_y_15_mau_thiet_ke_ho_ca_Koi_dep_ai_nhin_cung_me_so_11_52813f4d65/hinh_anh_goi_y_15_mau_thiet_ke_ho_ca_Koi_dep_ai_nhin_cung_me_so_11_52813f4d65.jpg",
    type: "Hình tròn",
    size: "100m2",
    location: "Hà Nội",
    price: "1000000",
    construction_time: "2 tháng",
    materials_used: "Đá tự nhiên, bê tông",
    water_feature: "Thác nước nhỏ",
  },
  {
    id: 2,
    name: "Koi Pond - Đà Nẵng",
    description: "Thiết kế hồ cá Koi hiện đại và hài hòa với thiên nhiên.",
    rating: 4.7,
    image: "https://sanvuonphuongdong.com.vn/wp-content/uploads/2024/07/449849691_122157011738236527_2279416121825365033_n.jpg",
    type: "Hình oval",
    size: "150m2",
    location: "Đà Nẵng",
    price: "2000000",
    construction_time: "3 tháng",
    materials_used: "Đá Granite, xi măng",
    water_feature: "Thác nước tầng",
  },
  {
    id: 3,
    name: "Koi Pond - TP.HCM",
    description: "Hồ cá Koi phong cách Nhật Bản.",
    rating: 4.8,
    image: "https://hocakoihcm.com/wp-content/uploads/2016/01/t.jpg",
    type: "Hình chữ nhật",
    size: "200m2",
    location: "TP.HCM",
    price: "3000000",
    construction_time: "4 tháng",
    materials_used: "Đá Bazan, sỏi trắng",
    water_feature: "Suối nhân tạo",
  },
  {
    id: 4,
    name: "Koi Pond - Vũng Tàu",
    description: "Hồ cá Koi với cảnh quan đẹp mắt và hệ sinh thái tự nhiên.",
    rating: 4.6,
    image: "https://honnonbomiennam.vn/wp-content/uploads/2022/05/47.jpg",
    type: "Hình chữ U",
    size: "250m2",
    location: "Vũng Tàu",
    price: "4000000",
    construction_time: "5 tháng",
    materials_used: "Đá xanh, sỏi biển",
    water_feature: "Hệ thống lọc nước tuần hoàn",
  },
  {
    id: 5,
    name: "Koi Pond - Hải Phòng",
    description: "Hồ cá Koi lớn với khả năng chống thấm tốt.",
    rating: 4.4,
    image: "https://sonsanepoxy.vn/wp-content/uploads/2022/11/goi-y-5-cach-chong-tham-ho-ca-koi-hieu-qua-cao-ben-dep-lau-dai-4.jpeg",
    type: "Hình vuông",
    size: "120m2",
    location: "Hải Phòng",
    price: "2500000",
    construction_time: "3 tháng",
    materials_used: "Đá Marble, bê tông",
    water_feature: "Đài phun nước",
  },
  {
    id: 6,
    name: "Koi Pond - Nha Trang",
    description: "Hồ cá Koi tích hợp với hệ thống cây cảnh.",
    rating: 4.9,
    image: "https://zenkoifarm.vn/wp-content/uploads/cay-trong-ho-ca-koi.jpg",
    type: "Hình lục giác",
    size: "180m2",
    location: "Nha Trang",
    price: "3500000",
    construction_time: "4 tháng",
    materials_used: "Gạch men, sỏi tự nhiên",
    water_feature: "Bể bơi cho cá Koi",
  },
  {
    id: 7,
    name: "Koi Pond - Biên Hòa",
    description: "Hồ cá Koi với hệ thống điều hòa nhiệt độ tự động.",
    rating: 4.5,
    image: "https://koilover.vn/uploads/thumbs/bien-phap-xu-ly-ho-ca-koi-bi-mat-diendien_20220714112858517.jpg",
    type: "Hình bầu dục",
    size: "220m2",
    location: "Biên Hòa",
    price: "3800000",
    construction_time: "5 tháng",
    materials_used: "Đá nhân tạo, kính cường lực",
    water_feature: "Cầu đá trên hồ",
  },
  {
    id: 8,
    name: "Koi Pond - Bình Dương",
    description: "Thiết kế hồ cá Koi kết hợp với khu vực thư giãn ngoài trời.",
    rating: 4.6,
    image: "https://storage.googleapis.com/digital-platform/hinh_anh_goi_y_15_mau_thiet_ke_ho_ca_Koi_dep_ai_nhin_cung_me_so_1_c8b8397ee5/hinh_anh_goi_y_15_mau_thiet_ke_ho_ca_Koi_dep_ai_nhin_cung_me_so_1_c8b8397ee5.jpg",
    type: "Hình vuông",
    size: "300m2",
    location: "Bình Dương",
    price: "4200000",
    construction_time: "6 tháng",
    materials_used: "Đá phiến, cát xây dựng",
    water_feature: "Hệ thống sục khí",
  },
  {
    id: 9,
    name: "Koi Pond - Huế",
    description: "Hồ cá Koi với cảnh quan nghệ thuật đậm chất cổ điển.",
    rating: 4.7,
    image: "https://cayplus.vn/wp-content/uploads/414417bff15f1101484e.jpg",
    type: "Hình elip",
    size: "250m2",
    location: "Huế",
    price: "3500000",
    construction_time: "5 tháng",
    materials_used: "Đá vôi, bê tông",
    water_feature: "Thác nước và hồ sen",
  },
  {
    id: 10,
    name: "Koi Pond - Cần Thơ",
    description: "Hồ cá Koi kết hợp vườn hoa quanh hồ.",
    rating: 4.9,
    image: "https://uploads-ssl.webflow.com/5d54d8964d608a130e2be670/5d75cfa8fc69ff0678e14e65_ca_koi15.jpg",
    type: "Hình ngôi sao",
    size: "320m2",
    location: "Cần Thơ",
    price: "5000000",
    construction_time: "6 tháng",
    materials_used: "Gạch đỏ, gỗ tự nhiên",
    water_feature: "Thác nước hai tầng",
  },
  {
    id: 11,
    name: "Koi Pond - Hội An",
    description: "Hồ cá Koi phong cách làng quê với cầu tre.",
    rating: 4.8,
    image: "https://vuadatrangtri.com/wp-content/uploads/2024/01/trang-tri-ho-ca-koi-dep_9.jpg",
    type: "Hình lục giác",
    size: "200m2",
    location: "Hội An",
    price: "3200000",
    construction_time: "4 tháng",
    materials_used: "Đá xanh, tre nứa",
    water_feature: "Suối nhân tạo",
  },
  {
    id: 12,
    name: "Koi Pond - Đà Lạt",
    description: "Thiết kế hồ cá Koi kết hợp thác nước và khu vườn Đà Lạt.",
    rating: 5.0,
    image: "https://hokoidep.com.vn/wp-content/uploads/2020/12/Thiet-ke-ho-ca-koi-Da-Lat-dep.jpg",
    type: "Hình trái tim",
    size: "280m2",
    location: "Đà Lạt",
    price: "4500000",
    construction_time: "6 tháng",
    materials_used: "Gỗ thông, đá tự nhiên",
    water_feature: "Thác nước cao",
  },
  {
    id: 13,
    name: "Koi Pond - Bắc Ninh",
    description: "Hồ cá Koi với cảnh quan tươi mát và hệ thống nước hiện đại.",
    rating: 4.4,
    image: "https://thanhphoxanh.vn/uploads/thanhphoxanh/news/2020/12/17/677cdb1b6ce13a1dbc6ec454611d6073.jpeg",
    type: "Hình tam giác",
    size: "170m2",
    location: "Bắc Ninh",
    price: "2800000",
    construction_time: "3 tháng",
    materials_used: "Đá Marble, sỏi trắng",
    water_feature: "Hệ thống lọc tuần hoàn",
  },
  {
    id: 14,
    name: "Koi Pond - Thanh Hóa",
    description: "Thiết kế hồ cá Koi đẹp mắt với cầu đá.",
    rating: 4.7,
    image: "https://lss.vn/wp-content/uploads/2023/04/25-mau-ho-ca-koi-dep-nhat-2023-phan-1-4.jpg",
    type: "Hình chữ L",
    size: "240m2",
    location: "Thanh Hóa",
    price: "3300000",
    construction_time: "5 tháng",
    materials_used: "Đá tự nhiên, sỏi đen",
    water_feature: "Thác nước tầng",
  },
  {
    id: 15,
    name: "Koi Pond - Bến Tre",
    description: "Thiết kế hồ cá Koi với tiểu cảnh cây bonsai.",
    rating: 4.6,
    image: "https://caycanhbancong.com/wp-content/uploads/2023/05/thiet-ke-ho-ca-koi.jpg",
    type: "Hình thoi",
    size: "210m2",
    location: "Bến Tre",
    price: "2900000",
    construction_time: "4 tháng",
    materials_used: "Đá nhân tạo, kính cường lực",
    water_feature: "Suối nhân tạo",
  },
  {
    id: 16,
    name: "Koi Pond - Long An",
    description: "Hồ cá Koi rộng lớn với hệ sinh thái cây xanh quanh hồ.",
    rating: 4.7,
    image: "https://storage.googleapis.com/digital-platform/hinh_anh_goi_y_15_mau_thiet_ke_ho_ca_Koi_dep_ai_nhin_cung_me_so_6_44b304f433/hinh_anh_goi_y_15_mau_thiet_ke_ho_ca_Koi_dep_ai_nhin_cung_me_so_6_44b304f433.jpg",
    type: "Hình oval",
    size: "350m2",
    location: "Long An",
    price: "5200000",
    construction_time: "6 tháng",
    materials_used: "Đá vôi, sỏi trắng",
    water_feature: "Thác nước lớn",
  },
  {
    id: 17,
    name: "Koi Pond - Lào Cai",
    description: "Hồ cá Koi trên núi với cảnh quan tuyệt đẹp.",
    rating: 4.8,
    image: "https://nonbo.net.vn/wp-content/uploads/2019/02/ho-ca-koi-ngoai-troi-mang-bau-khong-khi-xanh-mat.jpg",
    type: "Hình chữ nhật",
    size: "300m2",
    location: "Lào Cai",
    price: "4800000",
    construction_time: "6 tháng",
    materials_used: "Đá tự nhiên, xi măng",
    water_feature: "Thác nước 3 tầng",
  },
  {
    id: 18,
    name: "Koi Pond - Phú Quốc",
    description: "Thiết kế hồ cá Koi ven biển với không gian thoáng đãng.",
    rating: 4.9,
    image: "https://bizweb.dktcdn.net/thumb/grande/100/307/111/files/mau-ho-ca-koi-dep-5.jpg?v=1540568561670",
    type: "Hình elip",
    size: "400m2",
    location: "Phú Quốc",
    price: "5500000",
    construction_time: "7 tháng",
    materials_used: "Sỏi biển, đá phiến",
    water_feature: "Hệ thống phun sương",
  },
  {
    id: 19,
    name: "Koi Pond - Tây Ninh",
    description: "Hồ cá Koi kết hợp khu vườn sinh thái.",
    rating: 4.6,
    image: "https://greenmore.vn/wp-content/uploads/2018/10/ho-ca-koy-trong-san-vuon-greenmore-6.jpg",
    type: "Hình ngũ giác",
    size: "250m2",
    location: "Tây Ninh",
    price: "3500000",
    construction_time: "4 tháng",
    materials_used: "Đá bazan, gỗ tự nhiên",
    water_feature: "Hồ nhân tạo và suối",
  },
  {
    id: 20,
    name: "Koi Pond - Quảng Ninh",
    description: "Hồ cá Koi với cảnh quan xanh tươi và hệ thống đài phun nước.",
    rating: 4.7,
    image: "https://daiphunnuocvn.com/wp-content/uploads/2022/02/dai_phun_nuoc_ho_ca_koi__1_.jpg",
    type: "Hình oval",
    size: "270m2",
    location: "Quảng Ninh",
    price: "3800000",
    construction_time: "5 tháng",
    materials_used: "Đá xanh, gạch men",
    water_feature: "Đài phun nước lớn",
  },
  {
    id: 21,
    name: "Koi Pond - Đồng Nai",
    description: "Hồ cá Koi với thiết kế sang trọng và hiện đại.",
    rating: 4.5,
    image: "https://vuonhoa.vn/uploads/data/1098/files/news/Ho-ca-koi/1-ho-ca-koi-nhat-ban-dep-7.jpg",
    type: "Hình vuông",
    size: "230m2",
    location: "Đồng Nai",
    price: "3400000",
    construction_time: "4 tháng",
    materials_used: "Gạch men, đá tự nhiên",
    water_feature: "Thác nước và hệ thống lọc hiện đại",
  },
  {
    id: 22,
    name: "Koi Pond - Sóc Trăng",
    description: "Thiết kế hồ cá Koi với không gian cây cỏ tự nhiên bao quanh.",
    rating: 4.6,
    image: "https://static1.cafeland.vn/cafelandnew/hinh-anh/2021/07/31/159/image-20210731125955-1.jpeg",
    type: "Hình lục giác",
    size: "280m2",
    location: "Sóc Trăng",
    price: "3700000",
    construction_time: "5 tháng",
    materials_used: "Đá granite, bê tông",
    water_feature: "Thác nước nhỏ",
  },
  {
    id: 23,
    name: "Koi Pond - Hưng Yên",
    description: "Hồ cá Koi thiết kế đơn giản nhưng không kém phần tinh tế.",
    rating: 4.4,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQFRdipYhdVTpoAzcq6oZdJahmass9ebKDfA&s",
    type: "Hình chữ nhật",
    size: "190m2",
    location: "Hưng Yên",
    price: "3100000",
    construction_time: "4 tháng",
    materials_used: "Đá bazan, sỏi tự nhiên",
    water_feature: "Hồ nước tuần hoàn",
  },
  {
    id: 24,
    name: "Koi Pond - Thái Nguyên",
    description: "Thiết kế hồ cá Koi kết hợp vườn cây cảnh nghệ thuật.",
    rating: 4.7,
    image: "https://sanvuonadong.vn/wp-content/uploads/2020/08/thiet-ke-thi-cong-ho-ca-koi-1-san-vuon-a-dong-e1598590808619.jpg",
    type: "Hình bầu dục",
    size: "260m2",
    location: "Thái Nguyên",
    price: "3500000",
    construction_time: "5 tháng",
    materials_used: "Đá phiến, sỏi trắng",
    water_feature: "Thác nước đôi",
  },
  {
    id: 25,
    name: "Koi Pond - Vĩnh Long",
    description: "Hồ cá Koi với cảnh quan thiên nhiên hài hòa.",
    rating: 4.8,
    image: "https://nonbo.net.vn/wp-content/uploads/2019/02/ho_ca_koi_ngoai_troi_co_thac_nuoc.jpg",
    type: "Hình tam giác",
    size: "220m2",
    location: "Vĩnh Long",
    price: "3300000",
    construction_time: "4 tháng",
    materials_used: "Đá nhân tạo, xi măng",
    water_feature: "Suối nhỏ quanh hồ",
  },
  {
    id: 26,
    name: "Koi Pond - Ninh Thuận",
    description: "Thiết kế hồ cá Koi đẹp mắt và hệ thống lọc nước hiện đại.",
    rating: 4.9,
    image: "https://sanvuonvtop.vn/wp-content/uploads/2019/12/bang-gia-thi-cong-ho-ca-koi-4-min.jpg",
    type: "Hình ngũ giác",
    size: "310m2",
    location: "Ninh Thuận",
    price: "4200000",
    construction_time: "6 tháng",
    materials_used: "Đá tự nhiên, bê tông",
    water_feature: "Thác nước và hồ phun sương",
  },
  {
    id: 27,
    name: "Koi Pond - Quảng Ngãi",
    description:"Hồ cá Koi được thiết kế với phong cách hiện đại, thân thiện với môi trường.",
    rating: 4.7,
    image: "https://hokoidep.com.vn/wp-content/uploads/2021/08/Ho-ca-koi-goc-san-vuon-truoc-nha.jpg",
    type: "Hình vuông",
    size: "290m2",
    location: "Quảng Ngãi",
    price: "4000000",
    construction_time: "5 tháng",
    materials_used: "Gỗ tự nhiên, đá phiến",
    water_feature: "Hệ thống lọc nước và hồ cá",
  },
  {
    id: 28,
    name: "Koi Pond - Bình Định",
    description: "Hồ cá Koi rộng rãi với không gian xanh và thác nước lớn.",
    rating: 4.8,
    image: "https://thiconghocakoisaigon.com/upload/filemanager/1-3.png",
    type: "Hình elip",
    size: "350m2",
    location: "Bình Định",
    price: "4500000",
    construction_time: "6 tháng",
    materials_used: "Sỏi trắng, đá vôi",
    water_feature: "Thác nước lớn và hồ nhân tạo",
  },
  {
    id: 29,
    name: "Koi Pond - Quảng Nam",
    description: "Hồ cá Koi mang đậm nét văn hóa Nhật Bản.",
    rating: 4.9,
    image: "https://www.hancorp.com.vn/wp-content/uploads/2021/11/du-an-ho-ca-koi-1.jpg",
    type: "Hình trái tim",
    size: "200m2",
    location: "Quảng Nam",
    price: "3600000",
    construction_time: "5 tháng",
    materials_used: "Đá xanh, sỏi đen",
    water_feature: "Thác nước tầng",
  },
  {
    id: 30,
    name: "Koi Pond - Kiên Giang",
    description: "Hồ cá Koi thiết kế kết hợp với khu nghỉ dưỡng sinh thái.",
    rating: 5.0,
    image: "https://glid.vn/upload/images/DUAN/HOCAKOI/THI-CONG-HO-CA-KOI-HOA-BINH1.jpg",
    type: "Hình chữ L",
    size: "400m2",
    location: "Kiên Giang",
    price: "5500000",
    construction_time: "7 tháng",
    materials_used: "Đá tự nhiên, sỏi biển",
    water_feature: "Suối nhân tạo và hồ phun nước",
  },
];

export default listProject;
